name: asdc_ui
description: "UI for ASDC projects"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_secure_storage: ^9.0.0
  flutter_styled_toast: ^2.2.1
  mask_text_input_formatter: ^2.5.0
  material_color_utilities: ^0.11.1
  shared_preferences: ^2.2.1
  two_dimensional_scrollables: ^0.0.4
  intl: ^0.19.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^2.0.3
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  
  fonts:
    - family: Golos Text
      fonts:
        - asset: lib/fonts/Golos-Text/Golos-Text_Regular.ttf
          weight: 400
        - asset: lib/fonts/Golos-Text/Golos-Text_Medium.ttf
          weight: 500
        - asset: lib/fonts/Golos-Text/Golos-Text_DemiBold.ttf
          weight: 600
        - asset: lib/fonts/Golos-Text/Golos-Text_Bold.ttf
          weight: 700
        - asset: lib/fonts/Golos-Text/Golos-Text_Black.ttf
          weight: 900
    
    - family: Golos UI
      fonts:
        - asset: lib/fonts/Golos-UI/Golos-UI_Regular.ttf
          weight: 400
        - asset: lib/fonts/Golos-UI/Golos-UI_Medium.ttf
          weight: 500
        - asset: lib/fonts/Golos-UI/Golos-UI_Bold.ttf
          weight: 700